apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-deployment
  namespace: naman-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan-app-na
  template:
    metadata:
      labels:
        app: loan-app-na
    spec:
      containers:
        - name: loan-app-container
          image: na01/loanapp-nodejs
          ports:
            - containerPort: 3009
          env:
            - name: MONGODB_URI
              value: "mongodb://localhost:27017/LoanApplication"
        - name: mongo-db
          image: mongo:latest
          ports:
            - containerPort: 27017