apiVersion: v1
kind: Service
metadata:
  name: loan-svc
  namespace: naman-ns
spec:
  selector:
    app: loan-app-na
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 3009

    - name: mongo
      protocol: TCP
      port: 81
      targetPort: 27017
  type: LoadBalancer
  